### ISSUE TITLE
empty results

### ISSUE THREAD

**Issue by weizhiting** [Rappsilber-Laboratory/xi-mzidentml-converter#13]
Hi,  i use crux to search my mass data, and  upload mgf and mzid data , but alway get error? I just can not figure it out

**Comment by lars-kolbowski** [comment]
Hi,
easiest would be if you could provide me an example of a dataset that fails. Or copy paste the error log from the parsing. Otherwise I can only guess what's going wrong.

**Comment by weizhiting** [comment]
log id: md4tqsio9ijqb1tu8e0det2mm6_1544008241.log (include this in the github issue)
error type: Error
message: SpectrumIDFormat
id: undefined

this is the error log!  Thanks for your reply.

**Comment by lars-kolbowski** [comment]
I'm afraid your mzIdentML file is missing crucial information. I think it's not valid mzIdentML.
The SpectraData field(s) are missing the `SpectrumIDFormat`. It is necessary information on how to link the spectrumIDs from the identification file (mzid) to the peak list file. 
It's a required field according to mzIdentML schema since at least v1.1.0.
What software did you use to generate that mzIdentML? Does crux export it?
